adat1 = input(' szoveg ')
adat2 = int(input(' szam '))
adat3 = input(' szoveg2 ')
adat4 = float(input(' tizedes '))
print ('  ide jön a  '  +  adat1 +  ' ide jön a  '  ,adat2, ' ide jön a  '  +  adat3  +  ' ide jön a  '  ,adat4,)