print('1.feladat')
print('Szia '  + input('Neved?') + '!')
print('2.feladat')
print('**********')
print('oooooooooo')
print('3.feleadat')
print('*o*o*o*o*o')
print('*o*o*o*o*o')
print('4.feladat')
szam = int(input(' szam '))
szam2 = int(input(' szam2 '))
print ('szamold ki ezt ' ,szam+szam2)
print('5.feledat')
szam3 = int(input(' szam3 '))
szam4 = int(input(' szam4 '))
szam5 = int(input(' szam5 '))
print ('szamold ki ezeket is  ' ,szam3+szam4+szam5)